### ISSUE TITLE
problems when import v20

### ISSUE THREAD

**Issue by Truego** [oanda/v20-python#1]
Hi there
When I try to import v20, it saids like:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import v20
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/v20/**init**.py", line 2, in <module>
    import account
ImportError: No module named 'account'

Pls help me to figure it out. Ty

**Comment by hamx0r** [comment]
I haven't tried this with Python 3, but i can confirm it works on Python 2.7, and I'm using a Mac just like you!  Perhaps try 2.7?

**Comment by alekna** [comment]
I believe this issue has been solved long time ago so it can be closed.

**Comment by dmpettyp** [comment]
I agree, please re-open if this is still an issue
