### ISSUE TITLE
Can not get account list from api-fxtrade.oanda.com

### ISSUE THREAD

**Issue by ghost** [oanda/v20-python#19]
Has there been a change to the api-fxtrade.oanda.com/v3/accounts endpoint?

My code has stopped working on live but still works on demo. I'm using version 3.0.13 (have tried 12 and 11 with same result).

The command:
```
curl -H "Content-Type: application/json" -H "Authorization: Bearer <TOKEN>" "https://api-fxtrade.oanda.com/v3/accounts"
```
returns the correct result but the simple test.py below(with the same token and run from the same machine):
```
#!/usr/bin/env python

import v20 as oanda

api = oanda.Context('api-fxtrade.oanda.com', 443, True)
api.set_token('<TOKEN>')
res = api.account.list()
print res
```
fails with:
```
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    res = api.account.list()
  File "env/lib/python2.7/site-packages/v20/account.py", line 882, in list
    response = self.ctx.request(request)
  File "env/lib/python2.7/site-packages/v20/__init__.py", line 303, in request
    raise V20ConnectionError(url)
v20.errors.V20ConnectionError: Connection to v20 REST server at https://api-fxtrade.oanda.com:443/v3/accounts failed
```
and yet works fine against the demo site(with a demo token):
```
Method = GET
Path = https://api-fxpractice.oanda.com:443/v3/accounts
Status = 200
Reason = OK
Content-Type = application/json; charset=UTF-8
```
I've also regenerated the token for the live account several times with the same result.

Any help appreciated.

**Comment by dmpettyp** [comment]
Very strange, I ran your sample code and it worked just fine with 3.0.14 (which shouldn't be different from 3.0.13 with regards to connecting to the server). The problem you are experiencing seems to originate from the underlying requests library, and seems to be a problem establishing a connection to the server.  The fact that you can use curl from the same machine makes it even stranger.

**Comment by ghost** [comment]
Ok. New test:
```
#!/usr/bin/env python

import requests
url = 'https://api-fxtrade.oanda.com/v3/accounts'
headers = { 'Content-Type':  'application/json', 'Authorization': 'Bearer <TOKEN>' }
r = requests.get(url, headers=headers)
print r.json()
```
Brings back this error for api-fxtrade:
```
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
```
but works fine with api-fxpractice.

After a quick look at the two certificates I can not see any real difference which would lead one to be rejected over the other.

If I change the test script request line to:
```
r = requests.get(url, headers=headers, verify=False)
```
It runs fine albeit with a warning but hasn't solved the real problem.

I little bit of searching seems to be pointing the finger at SNI not being supported in any Python less then 2.7.9. The server I'm using is a CentOS 7 which ships with 2.7.5.

Quick side by side install of python 2.7.13 and... **same error**.

I'll keep looking.

**Comment by ghost** [comment]
Ok nailed it.

The package certifi is the culprit. Any version after 2015.4.28 boinks requests handling of the api-fxtrade.oanda.com certificate causing the error. Why it doesn't do the same for api-fxpractice I have no idea.

There is a long discussion about mitigations and causes here: [https://github.com/certifi/python-certifi/issues/26](url)

Thanks for the help @dmpettyp and a venting forum :)
