### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by joaofranca** [oanda/v20-python#2]
First of all, thank you for this helpful library. Nevertheless, it would be nice if there was some simple example using this.

**Comment by jorfermo** [comment]
Is there any place to get some code samples?

The link provided in the REST API docs is not working

http://developer.oanda.com/rest-live-v20/sample-code/
https://github.com/oanda/v20-python

**Comment by FlyCapital** [comment]
I think that api for v20 is not ready yet.

**Comment by dmpettyp** [comment]
The sample programs are under active development and can now be found at:

https://github.com/oanda/v20-python-samples
