### ISSUE TITLE
Stall streaming connections

### ISSUE THREAD

**Issue by alekna** [oanda/v20-python#8]
In your documentation you recommend that the client application should terminate the connection and re-connect its corresponding stream in the event of:
- No data has been received (no ticks, no heartbeats) from the rates stream for more than 10 seconds.
- No data has been received (no events, no heartbeats) from the events stream for more than 20 seconds.

None of these recommendations are implemented in v20 python wrapper. There's no way to set `v20.Content` timeout nor there is a way to catch stall connection. 

Please fix this.

**Comment by dmpettyp** [comment]
You should find this in 3.0.8 now. The defaults for both the price and transaction stream is set for 10 seconds which should be sufficient as heartbeats are sent out every 5 seconds

**Comment by alekna** [comment]
Could you please wrap `requests` exceptions within the wrapper code and throw your own exception like `StreamingConnectionError`.

At the moment I have to look for `requests.exceptions.ConnectionError`, `requests.exceptions.Timeout` and `requests.exceptions.HTTPError` being thrown at me. And I'm not even sure if that's the finite list of exceptions I might get when using your wrapper. It would be very nice if that was handled on your side.

**Comment by dmpettyp** [comment]
That's a good idea, as it would provide some wiggle-room if we every wanted to change the http lib used under the covers. I'll push some exception wrappers in the next release. How are you able to trigger a requests.exceptions.HTTPError? I've never seen one as a client of the v20 python library.

**Comment by alekna** [comment]
I'm not saying I ever managed to get this exception. This is just a theoretical possibility if you were ever to decide using `Response.raise_for_status()`.

**Comment by dmpettyp** [comment]
Fair enough. I'll do my best to wrap the exceptions that seem appropriate.

**Comment by dmpettyp** [comment]
3.0.9 is now up which wraps the exceptions. It also (for better or for worse) has stopped using reflection to generate the class members in the v20 object definitions in favour of being explicit and providing better documentation. This shouldn't be a be a breaking change (all of the sample code still behaves as expected).
