### ISSUE TITLE
Make JSON decoder pluggable

### ISSUE THREAD

**Issue by alekna** [oanda/v20-python#9]
You use built-in JSON decoder which is slow (except on PyPy)

Could you please make it pluggable/configurable so I that I could use faster decoder like `ujson`?

![screenshot from 2016-11-08 19-48-46](https://cloud.githubusercontent.com/assets/10272121/20114496/78f7d148-a5ec-11e6-94e9-f98b28a569ec.png)

**Comment by dmpettyp** [comment]
haha, the 3.0.9 release will already ujson by default. If you are desperate to have it pluggable I can do that, however I think just using ujson should be good enough.

**Comment by alekna** [comment]
I'm not desperate to have it pluggable. Just didn't want to impose my own choices on you :)

**Comment by alekna** [comment]
Some environments only allow use of third-party libraries that are pure Python code with no C extensions. Therefore I would like to suggest reverting back to built-in JSON library and making JSON decoder pluggable/configurable.
